# -*- coding: utf-8 -*-
"""Pattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sAchoppDXfzb2kgLnTG6vbXafb9C7A5_

##### Pattern.py
"""

# creating a variable for the object

pattern = '*'

# getting the first array

for num in range(1,10):
  if num <= 5:
   array = pattern * num

# getting the reverse array
  else:
     decend_pattern = 10 - num
     array = pattern * decend_pattern

  print(array)